// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHUk7LQcsJEINSOmo9ORpmW3148WMRRo',
    appId: '1:909706638402:web:0641e1d06713dec47469db',
    messagingSenderId: '909706638402',
    projectId: 'fir-9a1de',
    authDomain: 'fir-9a1de.firebaseapp.com',
    storageBucket: 'fir-9a1de.appspot.com',
    measurementId: 'G-K1MDQKMQNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrCFTQIDYr0f_AlZkGr_15my2janMyo4',
    appId: '1:909706638402:android:3546cadffd32e2c67469db',
    messagingSenderId: '909706638402',
    projectId: 'fir-9a1de',
    storageBucket: 'fir-9a1de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4yIj2OcyMT3gHcaeZZb-i0Yvmkzdck2g',
    appId: '1:909706638402:ios:7919285b907d096d7469db',
    messagingSenderId: '909706638402',
    projectId: 'fir-9a1de',
    storageBucket: 'fir-9a1de.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
